Work around cuda parameter space limit
Specifically, with previous commit we observe:

gpu_constructor.cpp(102): Error: Formal parameter space overflowed (5928 bytes required, max 4096 bytes allowed) in function _ZN3gpu26instantiateDeviceChemistryEP10GasMixture14ChemistryInputPv

which is happening b/c we increased gpudata::MAXREACTIONS, making
struct ChemistryInput too large for cuda to pass.  In general, need to
refactor how sizing and passing are handled in the gpu path to avoid
this kind of thing, but for now, we make the ChemistryInput struct
more efficient by using short int for the stoichimetric coefficients
(rather than double).