Fix array initialization error detected in hip build
Specifically,

M2ulPhyS.cpp:2084:16: error: variable-sized object may not be initialized

The values are set properly below, so the initialization was unnecessary anyway.